default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: <%= ENV['MALIINFO_DB_USER'] %>
  password: <%= ENV['MALIINFO_DB_PASSWORD'] %>

development:
  <<: *default
  database: maliinfo_dev

test: &test
  <<: *default
  database: maliinfo_test

production:
  adapter: postgresql
  url: <%= ENV['APPSDECK_POSTGRESQL_URL'] %>

